name: VRDL_HW
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _pytorch_select=0.2=gpu_0
  - blas=1.0=mkl
  - ca-certificates=2021.10.26=h06a4308_2
  - certifi=2021.10.8=py37h06a4308_0
  - cffi=1.14.6=py37h400218f_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - intel-openmp=2019.4=243
  - jpeg=9d=h7f8727e_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.2.0=h85742a9_0
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h27cfd23_0
  - lz4-c=1.9.3=h295c915_1
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37he8ac12f_0
  - mkl_fft=1.3.0=py37h54f3939_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.3=h7f8727e_0
  - ninja=1.10.2=hff7bd54_1
  - numpy=1.19.2=py37h54aff64_0
  - numpy-base=1.19.2=py37hfa32c7d_0
  - olefile=0.46=pyhd3eb1b0_0
  - openssl=1.1.1l=h7f8727e_0
  - pillow=8.4.0=py37h5aabda8_0
  - pip=21.2.2=py37h06a4308_0
  - pycparser=2.20=py_2
  - python=3.7.11=h12debd9_0
  - pytorch=1.5.1=py3.7_cuda10.1.243_cudnn7.6.3_0
  - readline=8.1=h27cfd23_0
  - setuptools=58.0.4=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - torchvision=0.6.1=py37_cu101
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==0.15.0
    - cachetools==4.2.4
    - charset-normalizer==2.0.7
    - contextlib2==21.6.0
    - cycler==0.11.0
    - flag==0.1.1
    - flags==0.0.1.2
    - fonttools==4.28.4
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - googledrivedownloader==0.4
    - grpcio==1.41.1
    - idna==3.3
    - imageio==2.13.5
    - importlib-metadata==4.8.1
    - kiwisolver==1.3.2
    - markdown==3.3.4
    - matplotlib==3.5.1
    - ml-collections==0.1.0
    - oauthlib==3.1.1
    - opencv-python==4.5.5.62
    - packaging==21.3
    - pandas==1.3.5
    - protobuf==3.19.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==3.0.6
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pyyaml==6.0
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scipy==1.2.2
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tqdm==4.62.3
    - typing-extensions==3.10.0.2
    - urllib3==1.26.7
    - werkzeug==2.0.2
    - zipp==3.6.0
prefix: /home/anatolios/anaconda3/envs/VRDL_HW

